### ISSUE TITLE
Add support for `GITHUB_API_URL` (GHES)

### ISSUE THREAD

**Issue by gr2m** [octokit/action.js#364]
See https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables.

**Comment by oscard0m** [comment]
> See https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables.

Is it solved by this line or is there something else I'm missing?
https://github.com/octokit/action.js/blob/24a544a612c98c85b51ee38d29ca34e638ef09f6/src/index.ts#L35

**Comment by gr2m** [comment]
Ha! All good then :) But I think we still don't properly test for it, would you like to do that? If not I can create a separate issue
